### ISSUE TITLE
Bsp Issue Aufwand 1 (ein aktivierter Note) 

### ISSUE THREAD

**Issue by redscarwolf** [redscarwolf/VR-Robot#1]
Hallo das ist ein Kommentar um zu testen. 
Hier kommt die aufgabenbeschreibung rein.

> hier ein Zitat

 Hinterlas doch auch einen um zu testen 🚨 👍 
`make clean`

**Comment by redscarwolf** [comment]
komentar von unten hinzugefügt. Hier kommen neuerungen oder probleme rein, die bei der bearbeitung des Issues auftreten

**Comment by jualtmey** [comment]
# Gelöst
Problem bearbeitet

**Comment by DanielHipp** [comment]
**Bug im Issue aufgetaucht!**

^- sollte sowas wirklich auftauchen, sollen wir dann wie ich es jetzt mache, das Issue erneut öffnen oder ein neues anlegen?

**Comment by redscarwolf** [comment]
@DanielHipp Ich denke bei dem Issue #1, kannst du den Bug glaub einfach wieder aufmachen. Außer wir wären schon in einem neuen Sprint dann könnte man einen neuen aufmachen und auf den alten verlinken. Aber im prinzip ist es egal, weil wir ja nicht abrechnen oder sonst wie zeit aufschreiben.
